/**
 * VerseTagger - Bible Translations Update Script
 *
 * Parses bible-versions.html file and generates
 * a TypeScript file with typed exports for use in the parser.
 */

import * as fs from 'fs';
import * as path from 'path';

/**
 * Bible version metadata for VerseTagger
 */
export interface BibleVersion {
  id: number;
  abbreviation: string;
  title: string;
}

/**
 * Parse Bible translations from HTML file
 * Extracts ID and VERSION from href="/bible/ID/JHN.1.VERSION"
 */
function parseTranslations(htmlPath: string): BibleVersion[] {
  console.log(`Reading HTML file: ${htmlPath}`);

  const htmlContent = fs.readFileSync(htmlPath, 'utf-8');

  // Regex to match href="/bible/ID/JHN.1.VERSION">Title
  // The pattern accounts for attributes before href and captures ID, VERSION, and title
  const regex = /href="\/bible\/(\d+)\/[A-Z]+\.\d+\.([^"]+)"[^>]*>([^<]+)</g;

  const translations: BibleVersion[] = [];
  let match: RegExpExecArray | null;

  while ((match = regex.exec(htmlContent)) !== null) {
    const id = parseInt(match[1], 10);
    const abbreviation = match[2];
    const title = match[3];

    // Clean up title (remove extra whitespace, special characters at end)
    const cleanTitle = title.trim().replace(/\s*✠\s*$/, '').trim();

    translations.push({
      id,
      abbreviation,
      title: cleanTitle
    });
  }

  console.log(`Successfully parsed ${translations.length} translations from HTML`);

  return translations;
}

/**
 * Escape single quotes in strings for TypeScript output
 */
function escapeString(str: string): string {
  return str.replace(/'/g, "\\'");
}

/**
 * Generate TypeScript file with Bible versions
 * Follows pattern from src/parser/book-mappings.ts
 */
function generateOutputFile(translations: BibleVersion[]): string {
  // Sort by ID for consistent output
  const sortedTranslations = [...translations].sort((a, b) => a.id - b.id);

  const lines: string[] = [];

  // Header comment
  lines.push('/**');
  lines.push(' * Bible version mappings for VerseTagger');
  lines.push(' * Generated by update-translations.ts');
  lines.push(` * Last updated: ${new Date().toISOString()}`);
  lines.push(' * Source: bible-versions.html (YouVersion Bible picker)');
  lines.push(' */');
  lines.push('');

  // Interface definition
  lines.push('/**');
  lines.push(' * Bible version metadata');
  lines.push(' */');
  lines.push('export interface BibleVersion {');
  lines.push('  /** YouVersion Bible ID */');
  lines.push('  id: number;');
  lines.push('  /** Version abbreviation (e.g., "NIV", "KJV") */');
  lines.push('  abbreviation: string;');
  lines.push('  /** Full version title */');
  lines.push('  title: string;');
  lines.push('}');
  lines.push('');

  // Array export
  lines.push('/**');
  lines.push(' * All available Bible versions (English only)');
  lines.push(' */');
  lines.push('export const BIBLE_VERSIONS: BibleVersion[] = [');

  sortedTranslations.forEach((version, index) => {
    const isLast = index === sortedTranslations.length - 1;
    lines.push('  {');
    lines.push(`    id: ${version.id},`);
    lines.push(`    abbreviation: '${escapeString(version.abbreviation)}',`);
    lines.push(`    title: '${escapeString(version.title)}'`);
    lines.push(`  }${isLast ? '' : ','}`);
  });

  lines.push('];');
  lines.push('');

  // Helper function for lookups (similar to buildBookLookup in book-mappings.ts)
  lines.push('/**');
  lines.push(' * Build lookup map for fast version resolution');
  lines.push(' */');
  lines.push('export function buildVersionLookup(): Map<string, BibleVersion> {');
  lines.push('  const lookup = new Map<string, BibleVersion>();');
  lines.push('');
  lines.push('  for (const version of BIBLE_VERSIONS) {');
  lines.push('    // Map by abbreviation (case-insensitive)');
  lines.push('    lookup.set(version.abbreviation.toUpperCase(), version);');
  lines.push('  }');
  lines.push('');
  lines.push('  return lookup;');
  lines.push('}');
  lines.push('');

  // Pre-built lookup
  lines.push('/**');
  lines.push(' * Pre-built version lookup map');
  lines.push(' */');
  lines.push('const versionLookup = buildVersionLookup();');
  lines.push('');

  lines.push('/**');
  lines.push(' * Find a Bible version by abbreviation (case-insensitive)');
  lines.push(' */');
  lines.push('export function findVersion(abbreviation: string): BibleVersion | undefined {');
  lines.push('  return versionLookup.get(abbreviation.toUpperCase());');
  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

/**
 * Write generated content to file
 */
function writeOutputFile(content: string, outputPath: string): void {
  const dir = path.dirname(outputPath);

  // Ensure directory exists
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  // Write file
  fs.writeFileSync(outputPath, content, 'utf-8');

  console.log(`✓ Generated ${outputPath}`);
}

/**
 * Main execution flow
 */
function main() {
  console.log('VerseTagger - Bible Translations Update Script');
  console.log('='.repeat(50));
  console.log('');

  try {
    // Step 1: Parse HTML file
    const htmlPath = path.join(__dirname, 'bible-versions.html');
    console.log('Parsing Bible translations from HTML file...');
    const translations = parseTranslations(htmlPath);
    console.log('✓ Parsed translations');
    console.log('');

    // Step 2: Generate TypeScript file
    console.log('Generating TypeScript file...');
    const content = generateOutputFile(translations);
    const outputPath = path.join(__dirname, 'src', 'parser', 'bible-versions.ts');
    writeOutputFile(content, outputPath);
    console.log('');

    // Summary
    console.log('='.repeat(50));
    console.log('✓ Update completed successfully!');
    console.log(`  Total versions: ${translations.length}`);
    console.log(`  Output file: ${outputPath}`);
    console.log('='.repeat(50));

  } catch (error) {
    console.error('');
    console.error('='.repeat(50));
    console.error('Error updating translations:');
    console.error(error instanceof Error ? error.message : String(error));
    console.error('='.repeat(50));
    process.exit(1);
  }
}

// Execute
main();
