/**
 * Bible version mappings for VerseTagger
 * Generated by update-translations.ts
 * Last updated: 2025-12-18T01:48:54.841Z
 * Source: bible-versions.html (YouVersion Bible picker)
 */

/**
 * Bible version metadata
 */
export interface BibleVersion {
  /** YouVersion Bible ID */
  id: number;
  /** Version abbreviation (e.g., "NIV", "KJV") */
  abbreviation: string;
  /** Full version title */
  title: string;
  /** Whether this version is licensed */
  licensed: boolean;
}

/**
 * All available Bible versions (English only)
 */
export const BIBLE_VERSIONS: BibleVersion[] = [
  {
    id: 1588,
    abbreviation: 'AMP',
    title: 'Amplified Bible',
    licensed: true
  },
  {
    id: 12,
    abbreviation: 'ASV',
    title: 'American Standard Version',
    licensed: true
  },
  {
    id: 3034,
    abbreviation: 'BSB',
    title: 'English: Berean Standard Bible',
    licensed: true
  },
  {
    id: 42,
    abbreviation: 'CPDV',
    title: 'Catholic Public Domain Version',
    licensed: true
  },
  {
    id: 2079,
    abbreviation: 'EASY',
    title: 'EasyEnglish Bible 2024',
    licensed: true
  },
  {
    id: 1932,
    abbreviation: 'FBV',
    title: 'Free Bible Version',
    licensed: true
  },
  {
    id: 2163,
    abbreviation: 'GNV',
    title: 'Geneva Bible',
    licensed: true
  },
  {
    id: 2660,
    abbreviation: 'LSV',
    title: 'Literal Standard Version',
    licensed: true
  },
  {
    id: 100,
    abbreviation: 'NASB',
    title: 'New American Standard Bible - NASB 1995',
    licensed: true
  },
  {
    id: 2692,
    abbreviation: 'NASB2020',
    title: 'New American Standard Bible - NASB',
    licensed: true
  },
  {
    id: 110,
    abbreviation: 'NIRV',
    title: "New International Reader's Version",
    licensed: true
  },
  {
    id: 111,
    abbreviation: 'NIV',
    title: 'New International Version',
    licensed: true
  },
  {
    id: 113,
    abbreviation: 'NIVUK',
    title: 'New International Version (Anglicised)',
    licensed: true
  },
  {
    id: 4455,
    abbreviation: 'NTBNBL2025',
    title: 'Benamanga',
    licensed: true
  },
  {
    id: 2530,
    abbreviation: 'PEV',
    title: 'Plain English Version',
    licensed: true
  },
  {
    id: 3427,
    abbreviation: 'TCENT',
    title: 'The Text-Critical English New Testament',
    licensed: true
  },
  {
    id: 130,
    abbreviation: 'TOJBT2011',
    title: 'The Orthodox Jewish Bible',
    licensed: true
  },
  {
    id: 1849,
    abbreviation: 'TPT',
    title: 'The Passion Translation',
    licensed: true
  },
  {
    id: 4533,
    abbreviation: 'WBTP',
    title: 'Afā Wanyɛnyɛ wu Nugé Wàpyóò',
    licensed: true
  },
  {
    id: 1204,
    abbreviation: 'WEBBE',
    title: 'World English Bible British Edition',
    licensed: true
  },
  {
    id: 206,
    abbreviation: 'WEBUS',
    title: "World English Bible, American English Edition, without Strong's Numbers",
    licensed: true
  },
  {
    id: 1209,
    abbreviation: 'WMB',
    title: 'World Messianic Bible',
    licensed: true
  },
  {
    id: 1207,
    abbreviation: 'WMBBE',
    title: 'World Messianic Bible British Edition',
    licensed: true
  },
  {
    id: 4253,
    abbreviation: 'AFV',
    title: 'A Faithful Version',
    licensed: false
  },
  {
    id: 8,
    abbreviation: 'AMPC',
    title: 'Amplified Bible, Classic Edition',
    licensed: false
  },
  {
    id: 31,
    abbreviation: 'BOOKS',
    title: 'The Books of the Bible NT',
    licensed: false
  },
  {
    id: 37,
    abbreviation: 'CEB',
    title: 'Common English Bible',
    licensed: false
  },
  {
    id: 392,
    abbreviation: 'CEV',
    title: 'Contemporary English Version',
    licensed: false
  },
  {
    id: 303,
    abbreviation: 'CEVDCI',
    title: 'Contemporary English Version Interconfessional Edition',
    licensed: false
  },
  {
    id: 294,
    abbreviation: 'CEVUK',
    title: 'Contemporary English Version (Anglicised) 2012',
    licensed: false
  },
  {
    id: 1275,
    abbreviation: 'CJB',
    title: 'Complete Jewish Bible',
    licensed: false
  },
  {
    id: 1713,
    abbreviation: 'CSB',
    title: 'Christian Standard Bible',
    licensed: false
  },
  {
    id: 4124,
    abbreviation: 'CSBA',
    title: 'Christian Standard Bible Anglicised',
    licensed: false
  },
  {
    id: 478,
    abbreviation: 'DARBY',
    title: "Darby's Translation 1890",
    licensed: false
  },
  {
    id: 55,
    abbreviation: 'DRC1752',
    title: 'Douay-Rheims Challoner Revision 1752',
    licensed: false
  },
  {
    id: 4224,
    abbreviation: 'EHV',
    title: 'Evangelical Heritage Version - 2021',
    licensed: false
  },
  {
    id: 406,
    abbreviation: 'ERV',
    title: 'Holy Bible: Easy-to-Read Version',
    licensed: false
  },
  {
    id: 59,
    abbreviation: 'ESV',
    title: 'English Standard Version 2025',
    licensed: false
  },
  {
    id: 3633,
    abbreviation: 'FNVNT',
    title: 'First Nations Version',
    licensed: false
  },
  {
    id: 416,
    abbreviation: 'GNBDC',
    title: 'Good News Bible (British) with DC section 2017',
    licensed: false
  },
  {
    id: 431,
    abbreviation: 'GNBDK',
    title: 'Good News Bible (British) Catholic Edition 2017',
    licensed: false
  },
  {
    id: 296,
    abbreviation: 'GNBUK',
    title: 'Good News Bible (British Version) 2017',
    licensed: false
  },
  {
    id: 68,
    abbreviation: 'GNT',
    title: 'Good News Translation',
    licensed: false
  },
  {
    id: 69,
    abbreviation: 'GNTD',
    title: 'Good News Translation (US Version)',
    licensed: false
  },
  {
    id: 70,
    abbreviation: 'GW',
    title: "GOD'S WORD",
    licensed: false
  },
  {
    id: 1047,
    abbreviation: 'GWC',
    title: 'St Paul from the Trenches 1916',
    licensed: false
  },
  {
    id: 72,
    abbreviation: 'HCSB',
    title: 'Holman Christian Standard Bible',
    licensed: false
  },
  {
    id: 1359,
    abbreviation: 'ICB',
    title: "International Children's Bible",
    licensed: false
  },
  {
    id: 1077,
    abbreviation: 'JUB',
    title: 'Jubilee Bible',
    licensed: false
  },
  {
    id: 1,
    abbreviation: 'KJV',
    title: 'King James Version',
    licensed: false
  },
  {
    id: 546,
    abbreviation: 'KJVAAE',
    title: 'King James Version with Apocrypha, American Edition',
    licensed: false
  },
  {
    id: 547,
    abbreviation: 'KJVAE',
    title: 'King James Version, American Edition',
    licensed: false
  },
  {
    id: 90,
    abbreviation: 'LEB',
    title: 'Lexham English Bible',
    licensed: false
  },
  {
    id: 3345,
    abbreviation: 'LSB',
    title: 'Legacy Standard Bible',
    licensed: false
  },
  {
    id: 1171,
    abbreviation: 'MEV',
    title: 'Modern English Version',
    licensed: false
  },
  {
    id: 4540,
    abbreviation: 'MP1562',
    title: 'Metrical Psalms and Scripture Selections 1562 (Sternhold and Hopkins)',
    licensed: false
  },
  {
    id: 1365,
    abbreviation: 'MP1650',
    title: 'Psalms of David in Metre 1650 (Scottish Psalter)',
    licensed: false
  },
  {
    id: 2593,
    abbreviation: 'MP1696',
    title: 'Metrical Psalms and Scripture Selections 1696 (Brady &amp; Tate)',
    licensed: false
  },
  {
    id: 3051,
    abbreviation: 'MP1781',
    title: 'Scottish Metrical Paraphrases 1781',
    licensed: false
  },
  {
    id: 97,
    abbreviation: 'MSG',
    title: 'The Message',
    licensed: false
  },
  {
    id: 463,
    abbreviation: 'NABRE',
    title: 'New American Bible, revised edition',
    licensed: false
  },
  {
    id: 105,
    abbreviation: 'NCV',
    title: 'New Century Version',
    licensed: false
  },
  {
    id: 107,
    abbreviation: 'NET',
    title: 'New English Translation',
    licensed: false
  },
  {
    id: 114,
    abbreviation: 'NKJV',
    title: 'New King James Version',
    licensed: false
  },
  {
    id: 116,
    abbreviation: 'NLT',
    title: 'New Living Translation',
    licensed: false
  },
  {
    id: 4249,
    abbreviation: 'NLTCE',
    title: 'New Living Translation Catholic Edition',
    licensed: false
  },
  {
    id: 2135,
    abbreviation: 'NMV',
    title: 'New Messianic Version Bible',
    licensed: false
  },
  {
    id: 2015,
    abbreviation: 'NRSV-CI',
    title: 'New Revised Standard Version Catholic Interconfessional',
    licensed: false
  },
  {
    id: 3523,
    abbreviation: 'NRSVUE',
    title: 'New Revised Standard Version Updated Edition 2021',
    licensed: false
  },
  {
    id: 3915,
    abbreviation: 'OYBCENGL',
    title: 'The third line (in English) translating the meaning of each word in the Orthodox Yiddish Brit Chadashah (New Testament)',
    licensed: false
  },
  {
    id: 4557,
    abbreviation: 'OYTNKHEG',
    title: 'English word for word translation of Orthodox Yiddish Tanakh (OYTANAKH)',
    licensed: false
  },
  {
    id: 4070,
    abbreviation: 'OYTORHEG',
    title: 'Translation into English of Orthodox Yiddish Torah (OYTORAH)',
    licensed: false
  },
  {
    id: 2753,
    abbreviation: 'RAD',
    title: 'Radiate New Testament',
    licensed: false
  },
  {
    id: 2020,
    abbreviation: 'RSV',
    title: 'Revised Standard Version',
    licensed: false
  },
  {
    id: 2017,
    abbreviation: 'RSV-C',
    title: 'Revised Standard Version Old Tradition 1952',
    licensed: false
  },
  {
    id: 3548,
    abbreviation: 'RSVCI',
    title: 'Revised Standard Version',
    licensed: false
  },
  {
    id: 477,
    abbreviation: 'RV1885',
    title: 'Revised Version 1885',
    licensed: false
  },
  {
    id: 1922,
    abbreviation: 'RV1895',
    title: 'Revised Version with Apocrypha 1885, 1895',
    licensed: false
  },
  {
    id: 3010,
    abbreviation: 'TEG',
    title: 'Isaiah 1830, 1842 (John Jones alias Ioan Tegid)',
    licensed: false
  },
  {
    id: 314,
    abbreviation: 'TLV',
    title: 'Tree of Life Version',
    licensed: false
  },
  {
    id: 316,
    abbreviation: 'TS2009',
    title: 'The Scriptures 2009',
    licensed: false
  },
  {
    id: 2407,
    abbreviation: 'WBMS',
    title: "Wycliffe's Bible with Modern Spelling",
    licensed: false
  },
  {
    id: 4108,
    abbreviation: 'YALL',
    title: "Y'all Version Bible",
    licensed: false
  },
  {
    id: 821,
    abbreviation: 'YLT98',
    title: "Young's Literal Translation 1898",
    licensed: false
  }
];

/**
 * Build lookup map for fast version resolution
 */
export function buildVersionLookup(): Map<string, BibleVersion> {
  const lookup = new Map<string, BibleVersion>();

  for (const version of BIBLE_VERSIONS) {
    // Map by abbreviation (case-insensitive)
    lookup.set(version.abbreviation.toUpperCase(), version);
  }

  return lookup;
}

/**
 * Pre-built version lookup map
 */
const versionLookup = buildVersionLookup();

/**
 * Find a Bible version by abbreviation (case-insensitive)
 */
export function findVersion(abbreviation: string): BibleVersion | undefined {
  return versionLookup.get(abbreviation.trim().toUpperCase());
}

/**
 * Get regex pattern for matching Bible version abbreviations
 * Returns a pattern that matches all valid translation abbreviations
 * Pattern is sorted by length (longest first) to ensure proper matching
 */
export function getTranslationsRegex(): string {
  const abbreviations = BIBLE_VERSIONS.map(v => v.abbreviation);

  // Sort by length (longest first) to match longer abbreviations before shorter ones
  abbreviations.sort((a, b) => b.length - a.length);

  // Escape special regex characters and join with |
  return abbreviations
    .map(abbr => abbr.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'))
    .join('|');
}
